name: food_gram_app
description: A new Flutter project.
publish_to: 'none'

version: 1.24.0+56

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ^3.38.3
dependencies:
  app_tracking_transparency: ^2.0.6
  auth_buttons: ^3.0.0
  auto_animated: ^3.2.0
  cached_network_image: ^3.3.0
  confetti: ^0.8.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  easy_debounce: ^2.0.3
  enum_to_string: ^2.0.1
  envied: ^1.0.0
  firebase_core: ^3.13.1
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^19.3.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  flutter_sliding_tutorial: ^2.0.0+1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  geolocator: ^10.1.0
  go_router: ^12.1.1
  google_mobile_ads: ^5.2.0
  google_sign_in: ^6.1.4
  hooks_riverpod: ^2.4.9
  image_cropper: ^8.1.0
  image_picker: ^1.0.4
  in_app_review: ^2.0.8
  intl: ^0.20.2
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.2.0+4
  logger: ^2.0.2+1
  lottie: ^3.3.1
  map_launcher: ^3.0.0
  maplibre_gl: ^0.20.0
  new_version_plus: ^0.0.11
  package_info_plus: ^4.0.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  photo_viewer: ^0.0.3
  purchases_flutter: ^8.4.0
  quickalert: ^1.1.0
  riverpod_annotation: ^2.0.0
  screenshot: ^3.0.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^5.0.0
  skeletonizer: ^2.1.0
  supabase_flutter: ^2.3.3
  timezone: ^0.10.1
  toastification: ^3.0.3
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.3
  envied_generator: ^1.0.0
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.5
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.6.0
  riverpod_lint: ^2.0.0
  yumemi_lints: ^3.1.0

dependency_overrides:
  analyzer_plugin: ^0.13.0

flutter_launcher_icons:
  android: true
  ios: true

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/splash/splash.png'
  android: true
  ios: true
  fullscreen: true
  android_12:
    image: 'assets/splash/splash.png'

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/
    - assets/image/
    - assets/splash/
    - assets/gif/
    - assets/trophy/
    - assets/lottie/
    - assets/map/
